name: flutter_boilerplate
description: Boilerplate for my flutter projects

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  shared_preferences: ^2.0.9
  binder: ^0.4.0
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
